print('Please input your information')
print()
print()
first_name=input('Please input your first name. ')
last_name=input('Please input your last name. ')
email_id=input('Please input your email id. ')
phone_number=input('Please input your phone number.')
job_title=input('Please input your job title. ')
id_num=input('Please input your id_num. ')
hair_color=input('please input your hair color. ')
eye_color=input('Please input your eye color. ')
month=input('Please input the month you started. ')
training=input('Please type YES if you have done training or NO. ')
print()
print()
print('your ID Card is')
print('-'*50 )
print(f"{first_name.title()}, {last_name.title()}.")
print(f"{job_title.title()}")
print(f'ID {id_num}')
print()
print(f'{email_id.lower()}')
print(phone_number)
print()
#the :number means the number of spaces after the term before the first curly bracket.
print(f'Hair Color: {hair_color.capitalize():15} Eyes: {eye_color.capitalize()}')
print(f'Month: {month.capitalize():20} Training: {training.capitalize()}')
print()
print('-'*50)
input('enter to exit')
